#!/bin/bash

c=50000

for dir in "./tao_06182024"/*/; do

	newdir="$(printf "%05d" $c)"

	if [ -d "$newdir" ]; then rm -rf "$newdir"; fi
	
	mkdir -p "./$newdir";
	ln -s "$dir" "./$newdir"
	

	c=$((c+1))
done
